package com.retrolad.ch12.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "developer")
public class Developer implements Serializable {

    public static final String FIND_ALL = "Developer.findAll";
    public static final String FIND_BY_ID = "Developer.findById";
    public static final String FIND_ALL_WITH_GAME = "Developer.findAllWithGame";

    // IDENTITY means id is generated by RDBMS
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name")
    private String name;

    // Temporal allows to use java.util.Date which
    // will farther be converted to java.sql.Date
    @Temporal(TemporalType.DATE)
    @Column(name = "founded")
    private Date founded;

    @Version
    @Column(name = "version")
    private int version;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getFounded() {
        return founded;
    }

    public void setFounded(Date founded) {
        this.founded = founded;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Override
    public String toString() {
        return "Developer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", founded=" + founded +
                ", version=" + version +
                '}';
    }
}